
serenity.project.name = Projecto para validar APK (Swag Labs)

webdriver.driver= appium
appium.hub = http://localhost:4723/wd/hub

####### Android CAPS ######
appium.automationName=uiautomator2
appium.platformName = Android
appium.platformVersion = 16.0
appium.deviceName  = Small Phone
appium.app = https://github.com/erbombas/csb-aut-examen/blob/main/Android.SauceLabs.Mobile.Sample.app.2.7.1.apk
appium.newCommandTimeout = 1000